export class UserEntity {
  readonly id?: string;
  name: string;
  email: string;
  passwordHash: string;

  // Public exibition data
  publicEmail?: string;
  whatsapp?: string;
  phone?: string;
  instagram?: string;
  facebook?: string;
  linkedin?: string;
  profileImage?: string;
  bio?: string;
  careerStartDate?: Date;
  creci?: string;
  gender?: string;
  specialties?: string[];

  // Control
  isActive?: boolean;

  // Relationships
  propertyIds?: string[];
  dynamicWebsiteId?: string;

  constructor(
    name: string,
    email: string,
    passwordHash: string,
    id?: string, // Generated by DB
    publicEmail?: string,
    whatsapp?: string,
    phone?: string,
    instagram?: string,
    facebook?: string,
    linkedin?: string,
    profileImage?: string,
    bio?: string,
    careerStartDate?: Date,
    creci?: string,
    gender?: string,
    isActive?: boolean,
    specialties?: string[],
    propertyIds?: string[],
    dynamicWebsiteId?: string,
  ) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.passwordHash = passwordHash;
    this.publicEmail = publicEmail;
    this.whatsapp = whatsapp;
    this.phone = phone;
    this.instagram = instagram;
    this.facebook = facebook;
    this.linkedin = linkedin;
    this.profileImage = profileImage;
    this.bio = bio;
    this.careerStartDate = careerStartDate;
    this.creci = creci;
    this.gender = gender;
    this.isActive = isActive;
    this.specialties = specialties;
    this.propertyIds = propertyIds;
    this.dynamicWebsiteId = dynamicWebsiteId;
  }
}
