export class UserEntity {
  readonly id?: string;
  name: string;
  email: string;
  passwordHash: string;

  // Control
  isActive?: boolean;

  // Relationships
  propertyIds?: string[];
  dynamicWebsiteId?: string;

  constructor(
    name: string,
    email: string,
    passwordHash: string,
    id?: string, // Generated by DB
    propertyIds?: string[],
    dynamicWebsiteId?: string,
  ) {
    this.id = id;
    this.name = name;
    this.email = email;
    this.passwordHash = passwordHash;
    this.propertyIds = propertyIds;
    this.dynamicWebsiteId = dynamicWebsiteId;
  }
}
