export const LEISURE = [
  'Academia',
  'Bar/Lounge',
  'Bicicletário',
  'Brinquedoteca',
  'Campo de Futebol',
  'Cat Place',
  'Churrasqueira',
  'Cinema',
  'Copa de Funcionários',
  'Coworking',
  'Crossfit',
  'Deck Molhado',
  'Elevador',
  'Escada Fitness',
  'Espaço Beauty',
  'Espaço Delivery',
  'Espaço gourmet',
  'Espaço Influencer',
  'Espaço kids',
  'Espaço para piqueniques',
  'Fire place',
  'Fitness Externo',
  'Forno de Pizza',
  'Garagem',
  'Hall de Entrada',
  'Horta',
  'Lavanderia',
  'Lounge',
  'Mercado 24hs',
  'Mini Mercado',
  'Mini Quadra',
  'Pet care',
  'Pet place',
  'Piscina',
  'Piscina adulto',
  'Piscina aquecida',
  'Piscina Coberta',
  'Piscina Infantil',
  'Playground',
  'Pomar',
  'Portaria',
  'Praça',
  'Praça de Leitura',
  'Praça do Fogo',
  'Private Pool House',
  'Quadra de Beach Tennis',
  'Quadra de Tênis',
  'Quadra Poliesportiva',
  'Quadra Recreativa',
  'Redário',
  'Rooftop',
  'Sala de leitura',
  'Sala de Massagem',
  'Sala de Reunião',
  'Salão de festas',
  'Salão de Jogos',
  'Salão de Jogos Adolescente',
  'Salão de Jogos Adulto',
  'Sauna',
  'Segurança',
  'Sky Lounge',
  'Solarium',
  'Spa',
  'Sports Bar',
  'Terraço',
  'Tomada para carro elétrico',
];
